### ISSUE TITLE
ValueError: GraphDef cannot be larger than 2GB.

### ISSUE THREAD

**Issue by jiaozizhao** [ameroyer/PIC#3]
Hi, every time I trained the model for epoch 55, there was an error like below. Do you know how to sovel it?...............
epoch 55/150 12-08_06-44: (avg_bpd: 2.561) (avg_bpd_val: 2.540)                               
Traceback (most recent call last):
  File "main.py", line 464, in <module>
    saver.save(sess, os.path.join(log_dir, "model.ckpt"))
  File "/home/jzhao/cross-platform/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1621, in save
    self.export_meta_graph(meta_graph_filename)
  File "/home/jzhao/cross-platform/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1653, in export_meta_graph
    graph_def=ops.get_default_graph().as_graph_def(add_shapes=True),
  File "/home/jzhao/cross-platform/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2997, in as_graph_def
    result, _ = self._as_graph_def(from_version, add_shapes)
  File "/home/jzhao/cross-platform/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2967, in _as_graph_def
    raise ValueError("GraphDef cannot be larger than 2GB.")
ValueError: GraphDef cannot be larger than 2GB.

**Comment by ameroyer** [comment]
Hello,

What kind of data are you running the model on and did you change the default parameters ?
This means that the graph built by Tensorflow is getting too large, which shouldn't happen with the default options normally.

**Comment by jiaozizhao** [comment]
I trained on my own data. I only changed the learning rate.

**Comment by ameroyer** [comment]
Hello,

What sizes are your images ? and how do you feed them to the graph ?

**Comment by jiaozizhao** [comment]
My images are resized 128*128 as yours. I feed them to the graph as you did.

**Comment by ameroyer** [comment]
Hello,

I think the problem was coming from repetitive Tensorboard summaries during generation. 

I've just pushed a few changes that should solve this issue
(it should also remove the "Object was never used" warnings you had)
